site_name: PyTorch Adapt
theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: imgs/TinyLogo.png
  favicon: imgs/Favicon.png


plugins:
- search
- section-index
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          filters: []
        rendering:
          show_root_heading: true
          show_source: true
          heading_level: 3
        setup_commands:
          - import sys
          - sys.path.append("src")
      watch:
      - src/pytorch_adapt
      selection:
        new_path_syntax: yes

markdown_extensions:
- toc:
    permalink: True
- pymdownx.highlight
- pymdownx.superfences


extra_css:
- css/style.css

repo_name: 'KevinMusgrave/pytorch-adapt'
repo_url: 'https://github.com/KevinMusgrave/pytorch-adapt'
