site_name: PyTorch Adapt
theme:
  name: 'material'
  palette:
      scheme: slate
      primary: 'green'
      accent: 'green'
  logo: imgs/TinyLogo.png
  favicon: imgs/Favicon.png
  # features:
    # - navigation.tabs
    # - toc.integrate # gets rid of table of contents on the right side of the page

nav:
- Overview: index.md
- Getting started: getting_started.md
- Papers implemented:
  - Unsupervised Domain Adaptation: algorithms/uda.md
  - Validators: algorithms/validators.md
- Code: code/


plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- mkdocstrings:
    watch:
    - src/pytorch_adapt
    handlers:
      python:
        setup_commands:
          - import sys
          - sys.path.append("src")
        rendering:
          show_root_toc_entry: false
- section-index
- literate-nav:
    nav_file: SUMMARY.md

markdown_extensions:
- toc:
    permalink: True
    toc_depth: 2
- pymdownx.highlight
- pymdownx.superfences


extra_css:
- css/style.css

repo_name: 'KevinMusgrave/pytorch-adapt'
repo_url: 'https://github.com/KevinMusgrave/pytorch-adapt'
