site_name: PyTorch Adapt
theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: imgs/TinyLogo.png
  favicon: imgs/Favicon.png

nav:
- Getting Started: getting_started.md 
- Code Reference: reference/


plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- mkdocstrings:
    watch:
    - src/pytorch_adapt
    handlers:
      python:
        setup_commands:
          - import sys
          - sys.path.append("src")
- section-index
- literate-nav:
    nav_file: SUMMARY.md

markdown_extensions:
- toc:
    permalink: True
- pymdownx.highlight
- pymdownx.superfences


extra_css:
- css/style.css

repo_name: 'KevinMusgrave/pytorch-adapt'
repo_url: 'https://github.com/KevinMusgrave/pytorch-adapt'
