site_name: PyTorch Adapt
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  logo: imgs/TinyLogo.png
  favicon: imgs/Favicon.png


plugins:
- search
- section-index
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          filters: []
        rendering:
          show_root_heading: true
          show_source: true
          heading_level: 3
        setup_commands:
          - import sys
          - sys.path.append("src")
      watch:
      - src/pytorch_adapt
      selection:
        new_path_syntax: yes

markdown_extensions:
- toc:
    permalink: True


extra_css:
- css/style.css

repo_name: 'KevinMusgrave/pytorch-adapt'
repo_url: 'https://github.com/KevinMusgrave/pytorch-adapt'
