name: meta_validators

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'

jobs:
  call-base-test-workflow:
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      module-to-test: meta_validators